<div>
    <livewire:inc.slider></livewire:inc.slider>
    <livewire:inc.about></livewire:inc.about>
    <livewire:inc.services></livewire:inc.services>
    <livewire:inc.portfolio></livewire:inc.portfolio>
    <livewire:inc.packages></livewire:inc.packages>
    <livewire:inc.payment></livewire:inc.payment>
    <livewire:inc.contact></livewire:inc.contact>
</div>
